site: jerwin
url: https://jerwin.dev
title: jerwin
description: notes
author:
  name: jerwin
  email: dontemailme@jerwin.dev
  url: https://jerwin.dev
permalink: pretty
timezone: Asia/Calcutta

baseurl: ""

highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: "syntax"

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-pwa-plugin

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

paginate: 20
paginate_path: "/page:num/"
