site: jonghoonpark
url: https://github.jonghoonpark.com
title: 박종훈 기술블로그
description: 공부하고 경험한 것을 기록합니다.
author:
  name: 박종훈
  email: dev@jonghoonpark.com
  linkedin: https://www.linkedin.com/in/dev-jonghoonpark
  url: https://jonghoonpark.com
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
